services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:latest

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

volumes:
  postgres_eshopdb:
