services:
  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_DB=eshopdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql

  seq:
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=seqadmin
    ports:
      - "5341:5341"
      - "9091:80" 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    