services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:latest

volumes:
  postgres_eshopdb: